server:
  port: 9090

spring:
  application:
    name: msa-architecture-zuul-server

#Config server
cloud:
  config:
    uri: http://localhost:8888
    name: msa-architecture-config-server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8170/eureka/
    healthcheck:
      enabled: true

#Zuul Routing
zuul:
  routes:
    coffeeOrder:
      path: /coffeeOrder/**
      serviceId: msa-coffee-order

    coffeeMember:
      path: /coffeeMember/**
      serviceId: msa-coffee-member

    coffeeStatus:
      path: /coffeeStatus/**
      serviceId: msa-coffee-status